apiVersion: apps/v1
kind: Deployment
metadata:
  name: abilities-service
spec:
  selector:
    matchLabels:
      app: abilities-service
  replicas: 1
  template:
    metadata:
      labels:
        app: abilities-service
    spec:
      imagePullSecrets:
        - name: do-registry
      containers:
      - name: abilities-service
        image: registry.digitalocean.com/mogpost/abilities-service
        ports:
        - containerPort: 5000